#5.1.3. Pandas 설치와 실행

In [ ]:
!pip install pandas

#Pandas가 설치되면 다음 키워드를 추가하여 애플리케이션에 가져옵니다.
보통 넘파이 별칭 ‘pd’을 사용한다.

In [ ]:
import pandas as pd
print(pd.__version__)

* 설치가 제대로 되었는지 확인하려면 Python을 실행한 후 아래 코드를 입력해 보자.

#예제1) 간단한 판다스를 활용 해 데이터프레임을 생성 해 보자.

In [ ]:
import pandas as pd  # Pandas 라이브러리 불러오기
# 샘플 데이터 생성 (딕셔너리 형태)
data = {
    "이름": ["철수", "영희", "민수", "수지", "지훈"],
    "나이": [25, 30, 22, 29, 31],
    "직업": ["학생", "회사원", "프리랜서", "디자이너", "개발자"]
}
# 데이터프레임 생성
df = pd.DataFrame(data)
# 데이터 출력
print(df)

#예제2) 기본 Series 생성-pd.Series()

In [ ]:
import pandas as pd

# 리스트로 Series 생성
a = [1, 7, 2]
myvar = pd.Series(a)

print(myvar)

#예제3) 인덱스를 사용한 값 접근

In [ ]:
# 첫 번째 값 접근
print(myvar[0])

#예제4) 사용자 지정 인덱스 활용하기

In [ ]:
import pandas as pd

# 인덱스를 사용자 정의
a = [1, 7, 2]
myvar = pd.Series(a, index=["x", "y", "z"])

print(myvar)
print(myvar["x"])  # 인덱스 'x'에 해당하는 값 출력

In [ ]:
print(myvar["x"])  # 인덱스 'x'에 해당하는 값 출력
print(myvar["y"])  # 인덱스 'y'에 해당하는 값 출력
print(myvar["z"])  # 인덱스 'z'에 해당하는 값 출력

#예제5) 데이터프레임 만들기

In [ ]:
import pandas as pd  # 판다스 라이브러리 불러오기

# 딕셔너리를 사용한 데이터 생성
data = {
    "이름": ["철수", "영희", "민수"],
    "나이": [15, 16, 14],
    "학년": ["중3", "고1", "중2"]
}

# DataFrame 생성
df = pd.DataFrame(data)
print(df)
# 행열 개수를 확인
print(df.shape)

print(df["이름"])

---
#5.3. 보물지도를 펼치자: 파일 읽기와 저장하기

#예제6)	csv파일 불러오기

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')
print(type(df))
print(df)

#예제7)	CSV 파일 저장

In [ ]:
df.to_csv("output.csv", index=False)  # index=False는 인덱스 숫자 제외

#예제8)	엑셀 파일 불러오기

In [ ]:
import pandas as pd

df = pd.read_excel("sample.xlsx", sheet_name="Sheet1", engine='openpyxl')
print(df)

---
#5.4. 단서 찾기: 데이터 구조 파악과 정리

#예제9)	데이터 구조 확인하기

In [ ]:
import pandas as pd

# CSV 파일 불러오기
df = pd.read_csv("ex05.csv")

# 데이터프레임 정보 확인
print(df.info())

#예제10)	데이터 샘플-상위5개를 확인해 보자.

In [ ]:
# 데이터 샘플 확인 (상위 5개)
print(df.head())

#예제11)	데이터 샘플-하위5개를 확인해 보자.

In [ ]:
print(df.tail())

#예제12)	데이터프레임의 행열 개수를 확인해 보자.

In [ ]:
print(df.shape)

#예제13)	데이터프레임의 열이름을 출력 해 보자.

In [ ]:
print(df.columns)

In [ ]:
print(list(df.columns))

In [ ]:
import pandas as pd

# CSV 파일 불러오기
df = pd.read_csv("data.csv")

print(df.info())

#예제14)	기본 통계 요약 = describe()

In [ ]:
print(df.describe())

#예제15)	특정 열의 통계 분석

In [ ]:
print(df["Age"].mean())  # 평균값
print(df["Age"].median())  # 중앙값
print(df["Age"].min())  # 최소값
print(df["Age"].max())  # 최대값

#예제16)	특정 조건을 만족하는 행(row) 선택

In [ ]:
# 나이가 30세 이상인 데이터 필터링
filtered_data = df[df["Age"] >= 30]
print(filtered_data)

#예제17)	여러 조건을 조합하여 데이터 필터링

In [ ]:
# 나이가 30세 이상이고, 부서가 'IT'인 데이터 선택
filtered_data = df[(df["Age"] >= 30) & (df["Department"] == "IT")]
print(filtered_data)

#예제18)	특정 행 선택 (iloc, loc 활용)

In [ ]:
# 첫 번째 행 선택 (iloc 사용)
first_row = df.iloc[0]
print(first_row)
# 특정 행과 열 선택 (iloc 사용)
subset = df.iloc[1:3, [0, 2]]  # 1~2번째 행에서 'Name'과 'Department' 열 선택
print(subset)

#예제19)	결측값 확인- df.isnull()

In [ ]:
print(df.isnull().sum())  # 각 열의 결측값 개수 출력

#예제20)	결측값을 특정 값으로 채우기 (fillna)

In [ ]:
df["Salary"].fillna(0, inplace=True)  # 결측값을 0으로 채움
print(df["Salary"])

#예제21)	결측값을 평균값으로 채우기

In [ ]:
df["Age"].fillna(df["Age"].mean(), inplace=True)  # 결측값을 평균 나이로 채움
print(df["Age"])

#예제22)	결측값이 포함된 행 삭제 (dropna)

In [ ]:
df.dropna(inplace=True)  # 결측값이 포함된 행 삭제

In [ ]:
print(df)

#예제23)	중복 데이터 확인-duplicated()

In [ ]:
print(df.duplicated().sum())  # 중복된 행의 개수 확인

#예제24)	중복 데이터 제거- drop_duplicates()

In [ ]:
df.drop_duplicates(inplace=True)  # 중복된 행 제거

#예제25)	특정 열을 기준으로 정렬

In [ ]:
# 'Age' 기준으로 오름차순 정렬
df_sorted = df.sort_values(by="Age", ascending=True)
print(df_sorted)

#예제26)	여러 개의 열 정렬

In [ ]:
# 'Department' 기준 오름차순, 같은 부서 내에서는 'Age' 기준으로 내림차순 정렬
df_sorted_multi = df.sort_values(by=["Department", "Age"], ascending=[True, False])
print(df_sorted_multi)

#예제27)	숫자열만 그룹화

In [ ]:
grouped = df.groupby("Department").mean(numeric_only=True)
print(grouped)

#예제28)	수동으로 숫자형 열만 선택해서 groupby() 수행

In [ ]:
grouped = df.groupby("Department")[["Age", "Salary", "Experience"]].mean()
print(grouped)

---
#5.5. 숨은 단서 찾기: 텍스트 데이터 다루기

#예제29)	df_doc 데이터프레임 생성

In [ ]:
# 실습용 예시 문장
document = [
    "온라인 강의 등록 관련 문의입니다.",
    "   학원 운영 시간 문의입니다.   ",
    "교통 카드 발급에 관한 문의입니다. ",
    "코로나 확산으로 인한 운영 변경 안내입니다.",
    "Online course 관련 질문입니다.",
    "    Taxi 운임 관련 문의입니다.   ",
    "버스 노선 변경 관련 문의입니다.   "
]
df_doc = pd.DataFrame(document, columns=["Text"])
print(df_doc)

#예제30)	문자열 앞뒤의 공백 제거

In [ ]:
document = [doc.strip() for doc in document]
print(document)

#예제31)	문자열 앞뒤의 공백 제거

In [ ]:
df_doc["Trimmed"] = df_doc["Text"].str.strip()
df_doc["Left Trimmed"] = df_doc["Text"].str.lstrip()
df_doc["Right Trimmed"] = df_doc["Text"].str.rstrip()
print(df_doc[["Text", "Trimmed", "Left Trimmed", "Right Trimmed"]])

#예제32)	‘문의’단어 포함 여부 확인

In [ ]:
# '문의' 단어가 포함된 행만 str.contains()를 사용하여 필터링
df_filtered = df_doc[df_doc["Text"].str.contains("문의", regex=False)]
print(df_filtered)

#예제33)	 "온라인"을 "Online"으로 변경 해 보자.

In [ ]:
document = [doc.replace("온라인", "Online") for doc in document]
print(document)

#예제34)	문장을 단어 단위로 나누기.

In [ ]:
tokenized = [doc.split() for doc in document]
print(tokenized)

#예제35)	데이터 타입 변경

In [ ]:
df_doc['Text'].astype('string')


#예제36)	문장의 영어를 대문자로 변경 해 보자.

In [ ]:
df_doc["Uppercase"] = df_doc["Text"].str.upper()  # 영어 대문자 변환
df_doc["Lowercase"] = df_doc["Text"].str.lower()  # 영어 소문자 변환
print(df_doc[["Text", "Uppercase", "Lowercase"]])

---
#실전예제

##5.6.1. 미션1 : CSV 파일에서 특정 조건 데이터 추출
> 5.6.1.	CSV 파일에서 데이터를 읽어 특정 조건의 데이터를 필터링하고 요약 통계를 작성해 보자.

In [ ]:
import pandas as pd

# 1. CSV 파일 읽기
df = pd.read_csv("/content/Salary.csv")

# 데이터 확인
print("원본 데이터:\n", df)

# 2. 조건 필터링: 나이가 30세 이상인 직원 선택
filtered_df = df[df["Age"] >= 30]
print("\n30세 이상 직원 데이터:\n", filtered_df)

# 3. 요약 통계 계산: 평균 나이와 급여 계산
average_age = filtered_df["Age"].mean()
average_salary = filtered_df["Salary"].mean()

print("\n30세 이상 직원의 요약 통계:")
print(f"평균 나이: {average_age}")
print(f"평균 급여: {average_salary}")

---
##5.6.2. 미션2 : 부서별 급여 및 연령 분석 및 Excel 저장


##예제38)	부서별 급여 및 연령 분석

In [ ]:
import pandas as pd

# 데이터셋 생성
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace"],
    "Age": [25, 30, 35, 40, 29, 50, 45],
    "Department": ["Sales", "IT", "HR", "Sales", "IT", "HR", "Sales"],
    "Salary": [50000, 70000, 60000, 80000, 72000, 90000, 85000]
}

# DataFrame 생성
df = pd.DataFrame(data)

# 1. 그룹화된 데이터 통계 계산
grouped = df.groupby("Department").agg(
    Average_Salary=("Salary", "mean"),
    Total_Salary=("Salary", "sum"),
    Average_Age=("Age", "mean"),
    Count=("Name", "count")
)

# 그룹화된 데이터 출력
print("그룹화된 데이터:\n", grouped)

# 2. 그룹화된 데이터를 Excel 파일로 저장
output_file = "grouped_statistics.xlsx"
grouped.to_excel(output_file, sheet_name="Statistics")

print(f"\nExcel 파일로 저장 완료: {output_file}")